version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
   
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092-9094:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      HOSTNAME_COMMAND:
        "echo $$HOSTNAME"
      PORT_COMMAND:
        "docker port $$(HOSTNAME) 9092/tcp | cut -d: -f2"
      KAFKA_LISTENERS:
        "INTERNAL://_{HOSTNAME_COMMAND}:9090,\
          EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS:
        "INTERNAL://_{HOSTNAME_COMMAND}:9090,\
         EXTERNAL://0.0.0.0:_{PORT_COMMAND}"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP:
        "INTERNAL:PLAINTEXT,\
          EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

# https://medium.com/big-data-engineering/hello-kafka-world-the-complete-guide-to-kafka-with-docker-and-python-f788e2588cfc
# https://medium.com/@marcelo.hossomi/running-kafka-in-docker-machine-64d1501d6f0b