version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
   
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    expose:
      - "9090"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: "INSIDE://0.0.0.0:9090,OUTSIDE://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "INSIDE://kafka:9090,OUTSIDE://172.17.0.1:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INSIDE:PLAINTEXT, OUTSIDE:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka1:
    image: wurstmeister/kafka
    ports:
      - "9093:9092"
    expose:
      - "9090"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: "INSIDE://0.0.0.0:9090,OUTSIDE://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "INSIDE://kafka1:9090,OUTSIDE://172.17.0.1:9093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INSIDE:PLAINTEXT, OUTSIDE:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka2:
    image: wurstmeister/kafka
    ports:
      - "9094:9092"
    expose:
      - "9090"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: "INSIDE://0.0.0.0:9090,OUTSIDE://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "INSIDE://kafka2:9090,OUTSIDE://172.17.0.1:9094"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INSIDE:PLAINTEXT, OUTSIDE:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      
    

# https://medium.com/big-data-engineering/hello-kafka-world-the-complete-guide-to-kafka-with-docker-and-python-f788e2588cfc
# https://medium.com/@marcelo.hossomi/running-kafka-in-docker-machine-64d1501d6f0b